# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configOptimizerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_ConfigOptimizerWindow(object):
    def setupUi(self, ConfigOptimizerWindow):
        ConfigOptimizerWindow.setObjectName("ConfigOptimizerWindow")
        ConfigOptimizerWindow.resize(295, 400)
        self.centralwidget = QtWidgets.QWidget(ConfigOptimizerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 180, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.save_configurations_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_configurations_button.setGeometry(QtCore.QRect(110, 340, 75, 23))
        self.save_configurations_button.setObjectName("save_configurations_button")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 210, 251, 126))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(32, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(32, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(249, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_tries = QtWidgets.QLabel(self.layoutWidget)
        self.label_tries.setObjectName("label_tries")
        self.horizontalLayout_8.addWidget(self.label_tries)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.input_tries = QtWidgets.QSpinBox(self.layoutWidget)
        self.input_tries.setMinimum(1)
        self.input_tries.setMaximum(10)
        self.input_tries.setObjectName("input_tries")
        self.horizontalLayout_8.addWidget(self.input_tries)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_iterations = QtWidgets.QLabel(self.layoutWidget)
        self.label_iterations.setObjectName("label_iterations")
        self.horizontalLayout_6.addWidget(self.label_iterations)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.input_iterations = QtWidgets.QSpinBox(self.layoutWidget)
        self.input_iterations.setMinimum(100)
        self.input_iterations.setMaximum(10000)
        self.input_iterations.setSingleStep(100)
        self.input_iterations.setObjectName("input_iterations")
        self.horizontalLayout_6.addWidget(self.input_iterations)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_method = QtWidgets.QLabel(self.layoutWidget)
        self.label_method.setObjectName("label_method")
        self.horizontalLayout_7.addWidget(self.label_method)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.method_selector = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.method_selector.sizePolicy().hasHeightForWidth())
        self.method_selector.setSizePolicy(sizePolicy)
        self.method_selector.setObjectName("method_selector")
        self.method_selector.addItem("")
        self.horizontalLayout_7.addWidget(self.method_selector)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 13, 251, 155))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(249, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_pop_size = QtWidgets.QLabel(self.layoutWidget1)
        self.label_pop_size.setObjectName("label_pop_size")
        self.horizontalLayout_2.addWidget(self.label_pop_size)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.input_pop_size = QtWidgets.QSpinBox(self.layoutWidget1)
        self.input_pop_size.setMinimum(10)
        self.input_pop_size.setMaximum(1000)
        self.input_pop_size.setSingleStep(10)
        self.input_pop_size.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.input_pop_size.setObjectName("input_pop_size")
        self.horizontalLayout_2.addWidget(self.input_pop_size)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_epochs = QtWidgets.QLabel(self.layoutWidget1)
        self.label_epochs.setObjectName("label_epochs")
        self.horizontalLayout_5.addWidget(self.label_epochs)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.input_epochs = QtWidgets.QSpinBox(self.layoutWidget1)
        self.input_epochs.setMinimum(10)
        self.input_epochs.setMaximum(1000)
        self.input_epochs.setSingleStep(10)
        self.input_epochs.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.input_epochs.setProperty("value", 10)
        self.input_epochs.setDisplayIntegerBase(10)
        self.input_epochs.setObjectName("input_epochs")
        self.horizontalLayout_5.addWidget(self.input_epochs)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Vo = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Vo.setObjectName("label_Vo")
        self.horizontalLayout_3.addWidget(self.label_Vo)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.input_mutation_rate = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_mutation_rate.sizePolicy().hasHeightForWidth())
        self.input_mutation_rate.setSizePolicy(sizePolicy)
        self.input_mutation_rate.setMinimumSize(QtCore.QSize(0, 0))
        self.input_mutation_rate.setMaximumSize(QtCore.QSize(60, 16777215))
        self.input_mutation_rate.setObjectName("input_mutation_rate")
        self.horizontalLayout_3.addWidget(self.input_mutation_rate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Vo_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Vo_2.setObjectName("label_Vo_2")
        self.horizontalLayout_4.addWidget(self.label_Vo_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.input_overwrite_rate = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_overwrite_rate.sizePolicy().hasHeightForWidth())
        self.input_overwrite_rate.setSizePolicy(sizePolicy)
        self.input_overwrite_rate.setMaximumSize(QtCore.QSize(60, 16777215))
        self.input_overwrite_rate.setObjectName("input_overwrite_rate")
        self.horizontalLayout_4.addWidget(self.input_overwrite_rate)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        ConfigOptimizerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ConfigOptimizerWindow)
        self.statusbar.setObjectName("statusbar")
        ConfigOptimizerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConfigOptimizerWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigOptimizerWindow)

    def retranslateUi(self, ConfigOptimizerWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfigOptimizerWindow.setWindowTitle(_translate("ConfigOptimizerWindow", "MainWindow"))
        self.save_configurations_button.setText(_translate("ConfigOptimizerWindow", "Salvar"))
        self.label_2.setText(_translate("ConfigOptimizerWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Algoritmo Numérico</span></p></body></html>"))
        self.label_tries.setText(_translate("ConfigOptimizerWindow", "Tentativas"))
        self.label_iterations.setText(_translate("ConfigOptimizerWindow", "Iterações"))
        self.label_method.setText(_translate("ConfigOptimizerWindow", "Método"))
        self.method_selector.setItemText(0, _translate("ConfigOptimizerWindow", "SLSQP"))
        self.label.setText(_translate("ConfigOptimizerWindow",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Algoritmo Genético</span></p></body></html>"))
        self.label_pop_size.setText(_translate("ConfigOptimizerWindow", "Tamanho da População"))
        self.label_epochs.setText(_translate("ConfigOptimizerWindow", "Iterações"))
        self.label_Vo.setText(_translate("ConfigOptimizerWindow", "Taxa de Mutação"))
        self.label_Vo_2.setText(_translate("ConfigOptimizerWindow", "Taxa de Sobrescrição"))
