# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transformerCreateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateTransformerWindow(object):
    def setupUi(self, CreateTransformerWindow):
        CreateTransformerWindow.setObjectName("CreateTransformerWindow")
        CreateTransformerWindow.resize(330, 438)
        CreateTransformerWindow.setMinimumSize(QtCore.QSize(330, 438))
        CreateTransformerWindow.setMaximumSize(QtCore.QSize(330, 438))
        CreateTransformerWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(CreateTransformerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_Np = QtWidgets.QSpinBox(self.centralwidget)
        self.input_Np.setGeometry(QtCore.QRect(190, 50, 42, 22))
        self.input_Np.setMaximum(200)
        self.input_Np.setObjectName("input_Np")
        self.input_Npp = QtWidgets.QSpinBox(self.centralwidget)
        self.input_Npp.setGeometry(QtCore.QRect(190, 80, 42, 22))
        self.input_Npp.setMaximum(200)
        self.input_Npp.setObjectName("input_Npp")
        self.buttonPrimaryCableSel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPrimaryCableSel.setGeometry(QtCore.QRect(190, 120, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPrimaryCableSel.sizePolicy().hasHeightForWidth())
        self.buttonPrimaryCableSel.setSizePolicy(sizePolicy)
        self.buttonPrimaryCableSel.setMinimumSize(QtCore.QSize(120, 25))
        self.buttonPrimaryCableSel.setMaximumSize(QtCore.QSize(120, 25))
        self.buttonPrimaryCableSel.setObjectName("buttonPrimaryCableSel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(121, 20))
        self.label.setMaximumSize(QtCore.QSize(141, 20))
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(40, 80, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setMinimumSize(QtCore.QSize(121, 20))
        self.label2.setMaximumSize(QtCore.QSize(141, 20))
        self.label2.setObjectName("label2")
        self.buttonVerify = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVerify.setGeometry(QtCore.QRect(100, 370, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonVerify.sizePolicy().hasHeightForWidth())
        self.buttonVerify.setSizePolicy(sizePolicy)
        self.buttonVerify.setMinimumSize(QtCore.QSize(120, 25))
        self.buttonVerify.setMaximumSize(QtCore.QSize(120, 25))
        self.buttonVerify.setObjectName("buttonVerify")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 120, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(80, 20))
        self.label_6.setMaximumSize(QtCore.QSize(141, 20))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.input_Nps = QtWidgets.QSpinBox(self.centralwidget)
        self.input_Nps.setGeometry(QtCore.QRect(180, 230, 42, 22))
        self.input_Nps.setMaximum(200)
        self.input_Nps.setObjectName("input_Nps")
        self.input_Ns = QtWidgets.QSpinBox(self.centralwidget)
        self.input_Ns.setGeometry(QtCore.QRect(180, 200, 42, 22))
        self.input_Ns.setMaximum(200)
        self.input_Ns.setObjectName("input_Ns")
        self.label2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label2_2.setGeometry(QtCore.QRect(30, 230, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_2.sizePolicy().hasHeightForWidth())
        self.label2_2.setSizePolicy(sizePolicy)
        self.label2_2.setMinimumSize(QtCore.QSize(121, 20))
        self.label2_2.setMaximumSize(QtCore.QSize(141, 20))
        self.label2_2.setObjectName("label2_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(121, 20))
        self.label_7.setMaximumSize(QtCore.QSize(141, 20))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 310, 16, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.buttonCoreSel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCoreSel.setGeometry(QtCore.QRect(180, 310, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCoreSel.sizePolicy().hasHeightForWidth())
        self.buttonCoreSel.setSizePolicy(sizePolicy)
        self.buttonCoreSel.setMinimumSize(QtCore.QSize(120, 25))
        self.buttonCoreSel.setMaximumSize(QtCore.QSize(120, 25))
        self.buttonCoreSel.setObjectName("buttonCoreSel")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(80, 20))
        self.label_5.setMaximumSize(QtCore.QSize(141, 20))
        self.label_5.setObjectName("label_5")
        self.buttonSecondaryCableSel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSecondaryCableSel.setGeometry(QtCore.QRect(180, 260, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSecondaryCableSel.sizePolicy().hasHeightForWidth())
        self.buttonSecondaryCableSel.setSizePolicy(sizePolicy)
        self.buttonSecondaryCableSel.setMinimumSize(QtCore.QSize(120, 25))
        self.buttonSecondaryCableSel.setMaximumSize(QtCore.QSize(120, 25))
        self.buttonSecondaryCableSel.setObjectName("buttonSecondaryCableSel")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(80, 20))
        self.label_8.setMaximumSize(QtCore.QSize(141, 20))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(7, 290, 311, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 150, 311, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 340, 311, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        CreateTransformerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateTransformerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfigura_es = QtWidgets.QMenu(self.menubar)
        self.menuConfigura_es.setObjectName("menuConfigura_es")
        CreateTransformerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateTransformerWindow)
        self.statusbar.setObjectName("statusbar")
        CreateTransformerWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(CreateTransformerWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(CreateTransformerWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOtimizador = QtWidgets.QAction(CreateTransformerWindow)
        self.actionOtimizador.setObjectName("actionOtimizador")
        self.actionFatores_de_Seguran_a = QtWidgets.QAction(CreateTransformerWindow)
        self.actionFatores_de_Seguran_a.setObjectName("actionFatores_de_Seguran_a")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuConfigura_es.addAction(self.actionOtimizador)
        self.menuConfigura_es.addAction(self.actionFatores_de_Seguran_a)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfigura_es.menuAction())

        self.retranslateUi(CreateTransformerWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateTransformerWindow)

    def retranslateUi(self, CreateTransformerWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateTransformerWindow.setWindowTitle(_translate("CreateTransformerWindow", "Transformador"))
        self.buttonPrimaryCableSel.setText(_translate("CreateTransformerWindow", "Escolher Cabo"))
        self.label.setText(_translate("CreateTransformerWindow", "Número de Espiras"))
        self.label2.setText(_translate("CreateTransformerWindow", "Número de Fios em Paralelo"))
        self.buttonVerify.setText(_translate("CreateTransformerWindow", "Verificar e Salvar"))
        self.label_6.setText(_translate("CreateTransformerWindow", "Cabo do Primário:"))
        self.label_2.setText(_translate("CreateTransformerWindow", "Primário"))
        self.label_4.setText(_translate("CreateTransformerWindow", "Secundário"))
        self.label2_2.setText(_translate("CreateTransformerWindow", "Número de Fios em Paralelo"))
        self.label_7.setText(_translate("CreateTransformerWindow", "Número de Espiras"))
        self.buttonCoreSel.setText(_translate("CreateTransformerWindow", "Escolher Núcleo"))
        self.label_5.setText(_translate("CreateTransformerWindow", "Núcleo:"))
        self.buttonSecondaryCableSel.setText(_translate("CreateTransformerWindow", "Escolher Cabo"))
        self.label_8.setText(_translate("CreateTransformerWindow", "Cabo do Primário:"))
        self.menuFile.setTitle(_translate("CreateTransformerWindow", "Componente"))
        self.menuConfigura_es.setTitle(_translate("CreateTransformerWindow", "Configurações"))
        self.actionNew.setText(_translate("CreateTransformerWindow", "Novo"))
        self.actionSave.setText(_translate("CreateTransformerWindow", "Salvar"))
        self.actionOtimizador.setText(_translate("CreateTransformerWindow", "Otimizador"))
        self.actionFatores_de_Seguran_a.setText(_translate("CreateTransformerWindow", "Fatores de Segurança"))
