# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 90, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_Topologia = QtWidgets.QLabel(self.centralwidget)
        self.label_Topologia.setGeometry(QtCore.QRect(30, 90, 51, 20))
        self.label_Topologia.setObjectName("label_Topologia")
        self.input_Vin = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Vin.setGeometry(QtCore.QRect(160, 140, 71, 20))
        self.input_Vin.setObjectName("input_Vin")
        self.label_Vin = QtWidgets.QLabel(self.centralwidget)
        self.label_Vin.setGeometry(QtCore.QRect(30, 140, 121, 20))
        self.label_Vin.setObjectName("label_Vin")
        self.label_Vo = QtWidgets.QLabel(self.centralwidget)
        self.label_Vo.setGeometry(QtCore.QRect(30, 170, 101, 20))
        self.label_Vo.setObjectName("label_Vo")
        self.input_Vo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Vo.setGeometry(QtCore.QRect(160, 170, 71, 20))
        self.input_Vo.setObjectName("input_Vo")
        self.label_DeltaIin = QtWidgets.QLabel(self.centralwidget)
        self.label_DeltaIin.setGeometry(QtCore.QRect(30, 230, 91, 21))
        self.label_DeltaIin.setObjectName("label_DeltaIin")
        self.input_DeltaIin = QtWidgets.QLineEdit(self.centralwidget)
        self.input_DeltaIin.setGeometry(QtCore.QRect(160, 230, 71, 20))
        self.input_DeltaIin.setObjectName("input_DeltaIin")
        self.label_DeltaVo = QtWidgets.QLabel(self.centralwidget)
        self.label_DeltaVo.setGeometry(QtCore.QRect(30, 260, 91, 21))
        self.label_DeltaVo.setObjectName("label_DeltaVo")
        self.input_DeltaVo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_DeltaVo.setGeometry(QtCore.QRect(160, 260, 71, 20))
        self.input_DeltaVo.setObjectName("input_DeltaVo")
        self.label_Vo_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Vo_2.setGeometry(QtCore.QRect(30, 200, 111, 20))
        self.label_Vo_2.setObjectName("label_Vo_2")
        self.input_Po = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Po.setGeometry(QtCore.QRect(160, 200, 71, 20))
        self.input_Po.setObjectName("input_Po")
        self.pushButtonOptimize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOptimize.setGeometry(QtCore.QRect(100, 350, 75, 23))
        self.pushButtonOptimize.setObjectName("pushButtonOptimize")
        self.pushButtonSwitchSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSwitchSel.setGeometry(QtCore.QRect(420, 70, 121, 23))
        self.pushButtonSwitchSel.setObjectName("pushButtonSwitchSel")
        self.pushButtonCapSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCapSel.setGeometry(QtCore.QRect(420, 150, 121, 23))
        self.pushButtonCapSel.setObjectName("pushButtonCapSel")
        self.pushButtonDiodeSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDiodeSel.setGeometry(QtCore.QRect(420, 110, 121, 23))
        self.pushButtonDiodeSel.setObjectName("pushButtonDiodeSel")
        self.pushButtonDissSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDissSel.setGeometry(QtCore.QRect(560, 110, 121, 23))
        self.pushButtonDissSel.setObjectName("pushButtonDissSel")
        self.pushButtonCableSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCableSel.setGeometry(QtCore.QRect(560, 150, 121, 23))
        self.pushButtonCableSel.setObjectName("pushButtonCableSel")
        self.pushButtonCoreSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCoreSel.setGeometry(QtCore.QRect(560, 70, 121, 23))
        self.pushButtonCoreSel.setObjectName("pushButtonCoreSel")
        self.label_ConfiguracoesDoOtimizador = QtWidgets.QLabel(self.centralwidget)
        self.label_ConfiguracoesDoOtimizador.setGeometry(QtCore.QRect(480, 30, 141, 20))
        self.label_ConfiguracoesDoOtimizador.setObjectName("label_ConfiguracoesDoOtimizador")
        self.input_JMax = QtWidgets.QLineEdit(self.centralwidget)
        self.input_JMax.setGeometry(QtCore.QRect(160, 290, 71, 20))
        self.input_JMax.setObjectName("input_JMax")
        self.label_JMax = QtWidgets.QLabel(self.centralwidget)
        self.label_JMax.setGeometry(QtCore.QRect(30, 290, 91, 21))
        self.label_JMax.setObjectName("label_JMax")
        self.label_ConfiguracoesDoOtimizador_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ConfiguracoesDoOtimizador_2.setGeometry(QtCore.QRect(70, 40, 141, 20))
        self.label_ConfiguracoesDoOtimizador_2.setObjectName("label_ConfiguracoesDoOtimizador_2")
        self.graphWidget = MplWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(370, 230, 360, 280))
        self.graphWidget.setMinimumSize(QtCore.QSize(360, 280))
        self.graphWidget.setObjectName("graphWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuIn_cio = QtWidgets.QMenu(self.menubar)
        self.menuIn_cio.setObjectName("menuIn_cio")
        self.menuBiblioteca = QtWidgets.QMenu(self.menubar)
        self.menuBiblioteca.setObjectName("menuBiblioteca")
        self.menuAdd_Component = QtWidgets.QMenu(self.menuBiblioteca)
        self.menuAdd_Component.setObjectName("menuAdd_Component")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSwitch = QtWidgets.QAction(MainWindow)
        self.actionSwitch.setObjectName("actionSwitch")
        self.actionDiode = QtWidgets.QAction(MainWindow)
        self.actionDiode.setObjectName("actionDiode")
        self.actionCapacitor = QtWidgets.QAction(MainWindow)
        self.actionCapacitor.setObjectName("actionCapacitor")
        self.actionCabl = QtWidgets.QAction(MainWindow)
        self.actionCabl.setObjectName("actionCabl")
        self.actionMagnetic_Core = QtWidgets.QAction(MainWindow)
        self.actionMagnetic_Core.setObjectName("actionMagnetic_Core")
        self.actionOtimizador = QtWidgets.QAction(MainWindow)
        self.actionOtimizador.setObjectName("actionOtimizador")
        self.menuIn_cio.addAction(self.actionNew)
        self.menuIn_cio.addAction(self.actionOpen)
        self.menuIn_cio.addAction(self.actionSave)
        self.menuAdd_Component.addAction(self.actionSwitch)
        self.menuAdd_Component.addAction(self.actionDiode)
        self.menuAdd_Component.addAction(self.actionCapacitor)
        self.menuAdd_Component.addAction(self.actionCabl)
        self.menuAdd_Component.addAction(self.actionMagnetic_Core)
        self.menuBiblioteca.addAction(self.menuAdd_Component.menuAction())
        self.menuSettings.addAction(self.actionOtimizador)
        self.menubar.addAction(self.menuIn_cio.menuAction())
        self.menubar.addAction(self.menuBiblioteca.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Boost Half Bridge"))
        self.label_Topologia.setText(_translate("MainWindow", "Topologia"))
        self.label_Vin.setText(_translate("MainWindow", "Tensão de Entrada (V)"))
        self.label_Vo.setText(_translate("MainWindow", "Tensão de Saída (V)"))
        self.label_DeltaIin.setText(_translate("MainWindow", "DeltaIinMax (A)"))
        self.label_DeltaVo.setText(_translate("MainWindow", "DeltaVoMax (V)"))
        self.label_Vo_2.setText(_translate("MainWindow", "Potência de Saída (W)"))
        self.pushButtonOptimize.setText(_translate("MainWindow", "Otimizar"))
        self.pushButtonSwitchSel.setText(_translate("MainWindow", "Escolher Chaves"))
        self.pushButtonCapSel.setText(_translate("MainWindow", "Escolher Capacitores"))
        self.pushButtonDiodeSel.setText(_translate("MainWindow", "Escolher Diodos"))
        self.pushButtonDissSel.setText(_translate("MainWindow", "Escolher Dissipadores"))
        self.pushButtonCableSel.setText(_translate("MainWindow", "Escolher Cabos"))
        self.pushButtonCoreSel.setText(_translate("MainWindow", "Escolher Núcleos"))
        self.label_ConfiguracoesDoOtimizador.setText(_translate("MainWindow", "Configurações do Otimizador"))
        self.label_JMax.setText(_translate("MainWindow", "JMax (A/m2)"))
        self.label_ConfiguracoesDoOtimizador_2.setText(_translate("MainWindow", "Parâmetros de Otimização"))
        self.menuIn_cio.setTitle(_translate("MainWindow", "File"))
        self.menuBiblioteca.setTitle(_translate("MainWindow", "Library"))
        self.menuAdd_Component.setTitle(_translate("MainWindow", "Add Component"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSwitch.setText(_translate("MainWindow", "Switch"))
        self.actionDiode.setText(_translate("MainWindow", "Diode"))
        self.actionCapacitor.setText(_translate("MainWindow", "Capacitor"))
        self.actionCabl.setText(_translate("MainWindow", "Cable"))
        self.actionMagnetic_Core.setText(_translate("MainWindow", "Magnetic Core"))
        self.actionOtimizador.setText(_translate("MainWindow", "Otimizador"))
from GUI.mplwidget import MplWidget
