# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 745)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1080, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = MplWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(670, 20, 360, 280))
        self.graphWidget.setMinimumSize(QtCore.QSize(360, 280))
        self.graphWidget.setObjectName("graphWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 301, 701))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ConfiguracoesDoOtimizador_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ConfiguracoesDoOtimizador_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ConfiguracoesDoOtimizador_2.setObjectName("label_ConfiguracoesDoOtimizador_2")
        self.verticalLayout.addWidget(self.label_ConfiguracoesDoOtimizador_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.label_Topologia = QtWidgets.QLabel(self.layoutWidget)
        self.label_Topologia.setObjectName("label_Topologia")
        self.horizontalLayout_10.addWidget(self.label_Topologia)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.label_ConfiguracoesDoOtimizador_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ConfiguracoesDoOtimizador_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ConfiguracoesDoOtimizador_3.setObjectName("label_ConfiguracoesDoOtimizador_3")
        self.verticalLayout.addWidget(self.label_ConfiguracoesDoOtimizador_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Vin = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Vin.sizePolicy().hasHeightForWidth())
        self.label_Vin.setSizePolicy(sizePolicy)
        self.label_Vin.setMinimumSize(QtCore.QSize(121, 20))
        self.label_Vin.setMaximumSize(QtCore.QSize(121, 20))
        self.label_Vin.setObjectName("label_Vin")
        self.horizontalLayout.addWidget(self.label_Vin)
        self.input_Vin = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Vin.setMinimumSize(QtCore.QSize(30, 20))
        self.input_Vin.setMaximumSize(QtCore.QSize(60, 20))
        self.input_Vin.setObjectName("input_Vin")
        self.horizontalLayout.addWidget(self.input_Vin)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Vo = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Vo.sizePolicy().hasHeightForWidth())
        self.label_Vo.setSizePolicy(sizePolicy)
        self.label_Vo.setMinimumSize(QtCore.QSize(121, 20))
        self.label_Vo.setMaximumSize(QtCore.QSize(121, 20))
        self.label_Vo.setObjectName("label_Vo")
        self.horizontalLayout_3.addWidget(self.label_Vo)
        self.input_Vo = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Vo.setMaximumSize(QtCore.QSize(60, 20))
        self.input_Vo.setObjectName("input_Vo")
        self.horizontalLayout_3.addWidget(self.input_Vo)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Vo_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Vo_2.sizePolicy().hasHeightForWidth())
        self.label_Vo_2.setSizePolicy(sizePolicy)
        self.label_Vo_2.setMinimumSize(QtCore.QSize(121, 20))
        self.label_Vo_2.setMaximumSize(QtCore.QSize(121, 20))
        self.label_Vo_2.setObjectName("label_Vo_2")
        self.horizontalLayout_4.addWidget(self.label_Vo_2)
        self.input_Po = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Po.setMaximumSize(QtCore.QSize(60, 20))
        self.input_Po.setObjectName("input_Po")
        self.horizontalLayout_4.addWidget(self.input_Po)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_DeltaIin = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DeltaIin.sizePolicy().hasHeightForWidth())
        self.label_DeltaIin.setSizePolicy(sizePolicy)
        self.label_DeltaIin.setMinimumSize(QtCore.QSize(121, 20))
        self.label_DeltaIin.setMaximumSize(QtCore.QSize(121, 20))
        self.label_DeltaIin.setObjectName("label_DeltaIin")
        self.horizontalLayout_5.addWidget(self.label_DeltaIin)
        self.input_DeltaIin = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_DeltaIin.setMaximumSize(QtCore.QSize(60, 20))
        self.input_DeltaIin.setObjectName("input_DeltaIin")
        self.horizontalLayout_5.addWidget(self.input_DeltaIin)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_DeltaVo = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DeltaVo.sizePolicy().hasHeightForWidth())
        self.label_DeltaVo.setSizePolicy(sizePolicy)
        self.label_DeltaVo.setMinimumSize(QtCore.QSize(121, 20))
        self.label_DeltaVo.setMaximumSize(QtCore.QSize(121, 20))
        self.label_DeltaVo.setObjectName("label_DeltaVo")
        self.horizontalLayout_6.addWidget(self.label_DeltaVo)
        self.input_DeltaVo = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_DeltaVo.setMaximumSize(QtCore.QSize(60, 20))
        self.input_DeltaVo.setObjectName("input_DeltaVo")
        self.horizontalLayout_6.addWidget(self.input_DeltaVo)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_JMax = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_JMax.sizePolicy().hasHeightForWidth())
        self.label_JMax.setSizePolicy(sizePolicy)
        self.label_JMax.setMinimumSize(QtCore.QSize(121, 20))
        self.label_JMax.setMaximumSize(QtCore.QSize(121, 20))
        self.label_JMax.setObjectName("label_JMax")
        self.horizontalLayout_7.addWidget(self.label_JMax)
        self.input_JMax = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_JMax.setMaximumSize(QtCore.QSize(60, 20))
        self.input_JMax.setObjectName("input_JMax")
        self.horizontalLayout_7.addWidget(self.input_JMax)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.save_design_features = QtWidgets.QPushButton(self.layoutWidget)
        self.save_design_features.setObjectName("save_design_features")
        self.horizontalLayout_9.addWidget(self.save_design_features)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem16)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.FullOptimizerTab = QtWidgets.QWidget()
        self.FullOptimizerTab.setObjectName("FullOptimizerTab")
        self.tabWidget.addTab(self.FullOptimizerTab, "")
        self.NumericOptimizerTab = QtWidgets.QWidget()
        self.NumericOptimizerTab.setObjectName("NumericOptimizerTab")
        self.tabWidget.addTab(self.NumericOptimizerTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem17)
        self.testButton = QtWidgets.QPushButton(self.layoutWidget)
        self.testButton.setObjectName("testButton")
        self.horizontalLayout_18.addWidget(self.testButton)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(450, 20, 121, 16))
        self.label.setObjectName("label")
        self.converterDescription = QtWidgets.QTextBrowser(self.centralwidget)
        self.converterDescription.setGeometry(QtCore.QRect(390, 50, 256, 192))
        self.converterDescription.setObjectName("converterDescription")
        self.optimize_button = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_button.setGeometry(QtCore.QRect(480, 280, 75, 23))
        self.optimize_button.setObjectName("optimize_button")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(330, 410, 251, 301))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem19)
        self.label_ConfiguracoesDoOtimizador_4 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ConfiguracoesDoOtimizador_4.sizePolicy().hasHeightForWidth())
        self.label_ConfiguracoesDoOtimizador_4.setSizePolicy(sizePolicy)
        self.label_ConfiguracoesDoOtimizador_4.setObjectName("label_ConfiguracoesDoOtimizador_4")
        self.horizontalLayout_19.addWidget(self.label_ConfiguracoesDoOtimizador_4)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem20)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem21)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem22)
        self.pushButtonSelC1 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelC1.sizePolicy().hasHeightForWidth())
        self.pushButtonSelC1.setSizePolicy(sizePolicy)
        self.pushButtonSelC1.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelC1.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelC1.setObjectName("pushButtonSelC1")
        self.horizontalLayout_26.addWidget(self.pushButtonSelC1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem23)
        self.pushButtonSelC2 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelC2.sizePolicy().hasHeightForWidth())
        self.pushButtonSelC2.setSizePolicy(sizePolicy)
        self.pushButtonSelC2.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelC2.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelC2.setObjectName("pushButtonSelC2")
        self.horizontalLayout_26.addWidget(self.pushButtonSelC2)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem24)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem25)
        self.pushButtonSelC3 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelC3.sizePolicy().hasHeightForWidth())
        self.pushButtonSelC3.setSizePolicy(sizePolicy)
        self.pushButtonSelC3.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelC3.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelC3.setObjectName("pushButtonSelC3")
        self.horizontalLayout_20.addWidget(self.pushButtonSelC3)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem26)
        self.pushButtonSelC4 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelC4.sizePolicy().hasHeightForWidth())
        self.pushButtonSelC4.setSizePolicy(sizePolicy)
        self.pushButtonSelC4.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelC4.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelC4.setObjectName("pushButtonSelC4")
        self.horizontalLayout_20.addWidget(self.pushButtonSelC4)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem27)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem28)
        self.pushButtonSelD3 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelD3.sizePolicy().hasHeightForWidth())
        self.pushButtonSelD3.setSizePolicy(sizePolicy)
        self.pushButtonSelD3.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelD3.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelD3.setObjectName("pushButtonSelD3")
        self.horizontalLayout_21.addWidget(self.pushButtonSelD3)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem29)
        self.pushButtonSelD4 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelD4.sizePolicy().hasHeightForWidth())
        self.pushButtonSelD4.setSizePolicy(sizePolicy)
        self.pushButtonSelD4.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelD4.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelD4.setObjectName("pushButtonSelD4")
        self.horizontalLayout_21.addWidget(self.pushButtonSelD4)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem30)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem31)
        self.pushButtonSelS1 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelS1.sizePolicy().hasHeightForWidth())
        self.pushButtonSelS1.setSizePolicy(sizePolicy)
        self.pushButtonSelS1.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelS1.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelS1.setObjectName("pushButtonSelS1")
        self.horizontalLayout_22.addWidget(self.pushButtonSelS1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem32)
        self.pushButtonSelS2 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelS2.sizePolicy().hasHeightForWidth())
        self.pushButtonSelS2.setSizePolicy(sizePolicy)
        self.pushButtonSelS2.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButtonSelS2.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelS2.setObjectName("pushButtonSelS2")
        self.horizontalLayout_22.addWidget(self.pushButtonSelS2)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem33)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem34)
        self.pushButtonSelLi = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelLi.sizePolicy().hasHeightForWidth())
        self.pushButtonSelLi.setSizePolicy(sizePolicy)
        self.pushButtonSelLi.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonSelLi.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelLi.setObjectName("pushButtonSelLi")
        self.horizontalLayout_23.addWidget(self.pushButtonSelLi)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem35)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem36)
        self.pushButtonSelLk = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelLk.sizePolicy().hasHeightForWidth())
        self.pushButtonSelLk.setSizePolicy(sizePolicy)
        self.pushButtonSelLk.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonSelLk.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelLk.setObjectName("pushButtonSelLk")
        self.horizontalLayout_24.addWidget(self.pushButtonSelLk)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem37)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem38)
        self.pushButtonSelTr = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelTr.sizePolicy().hasHeightForWidth())
        self.pushButtonSelTr.setSizePolicy(sizePolicy)
        self.pushButtonSelTr.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonSelTr.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSelTr.setObjectName("pushButtonSelTr")
        self.horizontalLayout_25.addWidget(self.pushButtonSelTr)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem39)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem40)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(620, 430, 241, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem41)
        self.label_ConfiguracoesDoOtimizador = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ConfiguracoesDoOtimizador.sizePolicy().hasHeightForWidth())
        self.label_ConfiguracoesDoOtimizador.setSizePolicy(sizePolicy)
        self.label_ConfiguracoesDoOtimizador.setObjectName("label_ConfiguracoesDoOtimizador")
        self.horizontalLayout_12.addWidget(self.label_ConfiguracoesDoOtimizador)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem42)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        spacerItem43 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem43)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem44)
        self.pushButtonSwitchSel = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSwitchSel.sizePolicy().hasHeightForWidth())
        self.pushButtonSwitchSel.setSizePolicy(sizePolicy)
        self.pushButtonSwitchSel.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonSwitchSel.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonSwitchSel.setObjectName("pushButtonSwitchSel")
        self.horizontalLayout_14.addWidget(self.pushButtonSwitchSel)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem46)
        self.pushButtonDiodeSel = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDiodeSel.sizePolicy().hasHeightForWidth())
        self.pushButtonDiodeSel.setSizePolicy(sizePolicy)
        self.pushButtonDiodeSel.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonDiodeSel.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonDiodeSel.setObjectName("pushButtonDiodeSel")
        self.horizontalLayout_13.addWidget(self.pushButtonDiodeSel)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem47)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem48)
        self.pushButtonCoreSel = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCoreSel.sizePolicy().hasHeightForWidth())
        self.pushButtonCoreSel.setSizePolicy(sizePolicy)
        self.pushButtonCoreSel.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonCoreSel.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonCoreSel.setObjectName("pushButtonCoreSel")
        self.horizontalLayout_16.addWidget(self.pushButtonCoreSel)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem49)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem50)
        self.pushButtonCableSel = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCableSel.sizePolicy().hasHeightForWidth())
        self.pushButtonCableSel.setSizePolicy(sizePolicy)
        self.pushButtonCableSel.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonCableSel.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonCableSel.setObjectName("pushButtonCableSel")
        self.horizontalLayout_15.addWidget(self.pushButtonCableSel)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem51)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem52)
        self.pushButtonCapSel = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCapSel.sizePolicy().hasHeightForWidth())
        self.pushButtonCapSel.setSizePolicy(sizePolicy)
        self.pushButtonCapSel.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButtonCapSel.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButtonCapSel.setObjectName("pushButtonCapSel")
        self.horizontalLayout_17.addWidget(self.pushButtonCapSel)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem53)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        spacerItem54 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem54)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        self.menuIn_cio = QtWidgets.QMenu(self.menubar)
        self.menuIn_cio.setObjectName("menuIn_cio")
        self.menuBiblioteca = QtWidgets.QMenu(self.menubar)
        self.menuBiblioteca.setObjectName("menuBiblioteca")
        self.menuAdd_Component = QtWidgets.QMenu(self.menuBiblioteca)
        self.menuAdd_Component.setObjectName("menuAdd_Component")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSwitch = QtWidgets.QAction(MainWindow)
        self.actionSwitch.setObjectName("actionSwitch")
        self.actionDiode = QtWidgets.QAction(MainWindow)
        self.actionDiode.setObjectName("actionDiode")
        self.actionCapacitor = QtWidgets.QAction(MainWindow)
        self.actionCapacitor.setObjectName("actionCapacitor")
        self.actionCabl = QtWidgets.QAction(MainWindow)
        self.actionCabl.setObjectName("actionCabl")
        self.actionMagnetic_Core = QtWidgets.QAction(MainWindow)
        self.actionMagnetic_Core.setObjectName("actionMagnetic_Core")
        self.actionConfigOptimizer = QtWidgets.QAction(MainWindow)
        self.actionConfigOptimizer.setObjectName("actionConfigOptimizer")
        self.actionSecurityConfig = QtWidgets.QAction(MainWindow)
        self.actionSecurityConfig.setObjectName("actionSecurityConfig")
        self.actionTransformador = QtWidgets.QAction(MainWindow)
        self.actionTransformador.setObjectName("actionTransformador")
        self.actionIndutor = QtWidgets.QAction(MainWindow)
        self.actionIndutor.setObjectName("actionIndutor")
        self.actionComo_funciona_o_otimizador = QtWidgets.QAction(MainWindow)
        self.actionComo_funciona_o_otimizador.setObjectName("actionComo_funciona_o_otimizador")
        self.actionComo_utilizar_o_otimizador = QtWidgets.QAction(MainWindow)
        self.actionComo_utilizar_o_otimizador.setObjectName("actionComo_utilizar_o_otimizador")
        self.actionCarregar_Arquivo = QtWidgets.QAction(MainWindow)
        self.actionCarregar_Arquivo.setObjectName("actionCarregar_Arquivo")
        self.actionComponentes = QtWidgets.QAction(MainWindow)
        self.actionComponentes.setObjectName("actionComponentes")
        self.menuIn_cio.addAction(self.actionNew)
        self.menuIn_cio.addAction(self.actionOpen)
        self.menuIn_cio.addAction(self.actionSave)
        self.menuAdd_Component.addAction(self.actionSwitch)
        self.menuAdd_Component.addAction(self.actionDiode)
        self.menuAdd_Component.addAction(self.actionCapacitor)
        self.menuAdd_Component.addAction(self.actionCabl)
        self.menuAdd_Component.addAction(self.actionMagnetic_Core)
        self.menuAdd_Component.addAction(self.actionTransformador)
        self.menuAdd_Component.addAction(self.actionIndutor)
        self.menuBiblioteca.addAction(self.menuAdd_Component.menuAction())
        self.menuBiblioteca.addAction(self.actionCarregar_Arquivo)
        self.menuSettings.addAction(self.actionConfigOptimizer)
        self.menuSettings.addAction(self.actionSecurityConfig)
        self.menuAjuda.addAction(self.actionComo_funciona_o_otimizador)
        self.menuAjuda.addAction(self.actionComo_utilizar_o_otimizador)
        self.menubar.addAction(self.menuIn_cio.menuAction())
        self.menubar.addAction(self.menuBiblioteca.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GPCO - General Power Converter Optimizer"))
        self.label_ConfiguracoesDoOtimizador_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Configuração do Conversor</span></p></body></html>"))
        self.label_Topologia.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Topologia</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Boost Half Bridge"))
        self.label_ConfiguracoesDoOtimizador_3.setText(_translate("MainWindow",
                                                                  "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Parâmetros de Projeto</span></p></body></html>"))
        self.label_Vin.setText(_translate("MainWindow", "Tensão de Entrada (V)"))
        self.label_Vo.setText(_translate("MainWindow", "Tensão de Saída (V)"))
        self.label_Vo_2.setText(_translate("MainWindow", "Potência de Saída (W)"))
        self.label_DeltaIin.setText(_translate("MainWindow", "DeltaIinMax (%)"))
        self.label_DeltaVo.setText(_translate("MainWindow", "DeltaVoMax (%)"))
        self.label_JMax.setText(_translate("MainWindow", "JMax (A/m2)"))
        self.save_design_features.setText(_translate("MainWindow", "Salvar Parâmetros"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FullOptimizerTab),
                                  _translate("MainWindow", "Otimização Completa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NumericOptimizerTab),
                                  _translate("MainWindow", "Otimização Específica"))
        self.testButton.setText(_translate("MainWindow", "Otimizar"))
        self.label.setText(_translate("MainWindow", "Descrição do Conversor"))
        self.optimize_button.setText(_translate("MainWindow", "Otimizar"))
        self.label_ConfiguracoesDoOtimizador_4.setText(_translate("MainWindow",
                                                                  "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Escolha dos Componentes</span></p></body></html>"))
        self.pushButtonSelC1.setText(_translate("MainWindow", "C1"))
        self.pushButtonSelC2.setText(_translate("MainWindow", "C2"))
        self.pushButtonSelC3.setText(_translate("MainWindow", "C3"))
        self.pushButtonSelC4.setText(_translate("MainWindow", "C4"))
        self.pushButtonSelD3.setText(_translate("MainWindow", "D3"))
        self.pushButtonSelD4.setText(_translate("MainWindow", "D4"))
        self.pushButtonSelS1.setText(_translate("MainWindow", "S1"))
        self.pushButtonSelS2.setText(_translate("MainWindow", "S2"))
        self.pushButtonSelLi.setText(_translate("MainWindow", "Indutor de Entrada"))
        self.pushButtonSelLk.setText(_translate("MainWindow", "Indutor Auxiliar"))
        self.pushButtonSelTr.setText(_translate("MainWindow", "Transformador"))
        self.label_ConfiguracoesDoOtimizador.setText(_translate("MainWindow",
                                                                "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Escolha dos Componentes</span></p></body></html>"))
        self.pushButtonSwitchSel.setText(_translate("MainWindow", "Escolher Chaves"))
        self.pushButtonDiodeSel.setText(_translate("MainWindow", "Escolher Diodos"))
        self.pushButtonCoreSel.setText(_translate("MainWindow", "Escolher Núcleos"))
        self.pushButtonCableSel.setText(_translate("MainWindow", "Escolher Cabos"))
        self.pushButtonCapSel.setText(_translate("MainWindow", "Escolher Capacitores"))
        self.menuIn_cio.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuBiblioteca.setTitle(_translate("MainWindow", "Biblioteca"))
        self.menuAdd_Component.setTitle(_translate("MainWindow", "Adicionar Componente"))
        self.menuSettings.setTitle(_translate("MainWindow", "Configurações"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.actionNew.setText(_translate("MainWindow", "Criar nova otimização"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Carregar parâmetros"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Salvar parâmetros"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSwitch.setText(_translate("MainWindow", "Switch"))
        self.actionDiode.setText(_translate("MainWindow", "Diode"))
        self.actionCapacitor.setText(_translate("MainWindow", "Capacitor"))
        self.actionCabl.setText(_translate("MainWindow", "Fio"))
        self.actionMagnetic_Core.setText(_translate("MainWindow", "Núcleo Magnético"))
        self.actionConfigOptimizer.setText(_translate("MainWindow", "Otimizador"))
        self.actionSecurityConfig.setText(_translate("MainWindow", "Fatores de Seguraça"))
        self.actionTransformador.setText(_translate("MainWindow", "Transformador"))
        self.actionIndutor.setText(_translate("MainWindow", "Indutor"))
        self.actionComo_funciona_o_otimizador.setText(_translate("MainWindow", "Como funciona o otimizador?"))
        self.actionComo_utilizar_o_otimizador.setText(_translate("MainWindow", "Como utilizar o otimizador?"))
        self.actionCarregar_Arquivo.setText(_translate("MainWindow", "Carregar Arquivo"))
        self.actionComponentes.setText(_translate("MainWindow", "Componentes"))


from GUI.Custom.mplwidget import MplWidget
