# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectSingleComponentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleComponentSelectWindow(object):
    def setupUi(self, SingleComponentSelectWindow):
        SingleComponentSelectWindow.setObjectName("SingleComponentSelectWindow")
        SingleComponentSelectWindow.resize(411, 478)
        self.centralwidget = QtWidgets.QWidget(SingleComponentSelectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(140, 330, 61, 23))
        self.select_button.setObjectName("select_button")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setGeometry(QtCore.QRect(20, 100, 113, 20))
        self.search_input.setObjectName("search_input")
        self.list_available = QtWidgets.QListView(self.centralwidget)
        self.list_available.setGeometry(QtCore.QRect(20, 130, 181, 192))
        self.list_available.setObjectName("list_available")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 100, 161, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(210, 330, 61, 23))
        self.remove_button.setObjectName("remove_button")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(140, 100, 61, 23))
        self.search_button.setObjectName("search_button")
        self.list_selected = QtWidgets.QListView(self.centralwidget)
        self.list_selected.setGeometry(QtCore.QRect(210, 130, 181, 192))
        self.list_selected.setObjectName("list_selected")
        SingleComponentSelectWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SingleComponentSelectWindow)
        self.statusbar.setObjectName("statusbar")
        SingleComponentSelectWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SingleComponentSelectWindow)
        QtCore.QMetaObject.connectSlotsByName(SingleComponentSelectWindow)

    def retranslateUi(self, SingleComponentSelectWindow):
        _translate = QtCore.QCoreApplication.translate
        SingleComponentSelectWindow.setWindowTitle(_translate("SingleComponentSelectWindow", "MainWindow"))
        self.select_button.setText(_translate("SingleComponentSelectWindow", "Selecionar"))
        self.label.setText(_translate("SingleComponentSelectWindow", "Selecionado"))
        self.remove_button.setText(_translate("SingleComponentSelectWindow", "Remover"))
        self.search_button.setText(_translate("SingleComponentSelectWindow", "Pesquisar"))
